// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksManager.Data;

namespace TasksManager.Data.Migrations
{
    [DbContext(typeof(TasksManagerContext))]
    [Migration("20220515235442_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TasksManager.Data.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("Bit");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4677755-b803-41f1-9908-78b596992bb2"),
                            Description = "Description for Task 1",
                            IsCompleted = false,
                            Title = "Task #1"
                        },
                        new
                        {
                            Id = new Guid("ae5f3e13-62bf-4c2f-8455-02107a8fb1d4"),
                            Description = "Description for Task 2",
                            IsCompleted = false,
                            Title = "Task #2"
                        },
                        new
                        {
                            Id = new Guid("df95e8d0-9965-4cbe-a6f7-924c4d2e64db"),
                            Description = "Description for Task 3",
                            IsCompleted = false,
                            Title = "Task #3"
                        },
                        new
                        {
                            Id = new Guid("09dbc7bf-8752-4f1e-8c4a-f547fbccff29"),
                            Description = "Description for Task 4",
                            IsCompleted = false,
                            Title = "Task #4"
                        },
                        new
                        {
                            Id = new Guid("16626d47-3461-4f13-87de-369a4fdd0a18"),
                            Description = "Description for Task 5",
                            IsCompleted = false,
                            Title = "Task #5"
                        },
                        new
                        {
                            Id = new Guid("1edf5d30-d6c9-4612-995c-2d44be3ca896"),
                            Description = "Description for Task 6",
                            IsCompleted = false,
                            Title = "Task #6"
                        },
                        new
                        {
                            Id = new Guid("7387e595-5220-4768-9a4a-03da27a716fe"),
                            Description = "Description for Task 7",
                            IsCompleted = false,
                            Title = "Task #7"
                        },
                        new
                        {
                            Id = new Guid("662df157-1df3-4203-9168-351dd8beba6c"),
                            Description = "Description for Task 8",
                            IsCompleted = false,
                            Title = "Task #8"
                        },
                        new
                        {
                            Id = new Guid("0cd28c87-dc9e-4f8e-83d0-c6d86e717c56"),
                            Description = "Description for Task 8",
                            IsCompleted = false,
                            Title = "Task #9"
                        },
                        new
                        {
                            Id = new Guid("3c3239ed-561a-443c-a789-35958f902b2a"),
                            Description = "Description for Task 8",
                            IsCompleted = false,
                            Title = "Task #10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
